//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewGroupMenu
    {
        public int Id { get; set; }
        public string Role_Name { get; set; }
        public string Role_Desccription { get; set; }
        public int MenuId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string NavigationName { get; set; }
        public string Url { get; set; }
        public Nullable<int> Order_no { get; set; }
        public string IsCreated { get; set; }
        public string IsRead { get; set; }
        public string IsUpdate { get; set; }
        public string IsDelete { get; set; }
    }
}
