//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTask.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MyTaskEntities : DbContext
    {
        public MyTaskEntities()
            : base("name=MyTaskEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Detail_Users> Detail_Users { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<Master_CategoryProject> Master_CategoryProject { get; set; }
        public virtual DbSet<Master_Menus> Master_Menus { get; set; }
        public virtual DbSet<Master_Roles> Master_Roles { get; set; }
        public virtual DbSet<Master_Status> Master_Status { get; set; }
        public virtual DbSet<Master_Users> Master_Users { get; set; }
        public virtual DbSet<MenuRole> MenuRoles { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<ViewGroupMenu> ViewGroupMenus { get; set; }
        public virtual DbSet<ViewGroupUser> ViewGroupUsers { get; set; }
    
        [DbFunction("MyTaskEntities", "fnGetuserbyUsername")]
        public virtual IQueryable<fnGetuserbyUsername_Result> fnGetuserbyUsername(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnGetuserbyUsername_Result>("[MyTaskEntities].[fnGetuserbyUsername](@Username)", usernameParameter);
        }
    
        public virtual int spSendEmail()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSendEmail");
        }
    }
}
