//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTask.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ID { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> CategoryProject_Id { get; set; }
        public string ProjectDescription { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> ProjectStart { get; set; }
        public Nullable<System.DateTime> ProjectFinish { get; set; }
        public string ProjectLogo { get; set; }
    }
}
